[tools]
rust = "latest"

[tasks]
test = "cargo test"
build = "cargo build"
run = "cargo run"
check = "cargo check"
fmt = "cargo fmt"
clippy = "cargo clippy"

book = 'cargo run {{arg(name="file")}} --scale-d 120 && typst compile book.typ'

all = '''
cargo run -- --scale-d 120 data/frankenstein.txt && typst compile book.typ out/frankenstein.pdf
cargo run -- --scale-d 120 data/cloudstreet.txt && typst compile book.typ out/cloudstreet.pdf
cargo run -- --scale-d 120 --n 2 data/dr-seuss.txt && typst compile book.typ out/dr-seuss-2.pdf
cargo run -- --scale-d 120 --n 3 data/dr-seuss.txt && typst compile book.typ out/dr-seuss-3.pdf
cargo run -- --scale-d 120 --n 4 data/dr-seuss.txt && typst compile book.typ out/dr-seuss-4.pdf
echo "All processing complete!"
'''
